// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.59.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'package:meta/meta.dart';
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:meta/meta.dart';
import 'dart:ffi' as ffi;

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<String> trainKnn(
      {required int k, required List<LabeledImage> examples, dynamic hint}) {
    var arg0 = api2wire_usize(k);
    var arg1 = _platform.api2wire_list_labeled_image(examples);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_train_knn(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      constMeta: kTrainKnnConstMeta,
      argValues: [k, examples],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kTrainKnnConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "train_knn",
        argNames: ["k", "examples"],
      );

  Future<String> classifyKnn({required Uint8List img, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_classify_knn(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kClassifyKnnConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kClassifyKnnConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "classify_knn",
        argNames: ["img"],
      );

  Future<bool> kmeansReady({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_kmeans_ready(port_),
      parseSuccessData: _wire2api_bool,
      constMeta: kKmeansReadyConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kKmeansReadyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "kmeans_ready",
        argNames: [],
      );

  Future<int> trainingTime({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_training_time(port_),
      parseSuccessData: _wire2api_i64,
      constMeta: kTrainingTimeConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kTrainingTimeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "training_time",
        argNames: [],
      );

  Future<ImageResponse> intensityRgba(
      {required Uint8List intensities, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(intensities);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_intensity_rgba(port_, arg0),
      parseSuccessData: _wire2api_image_response,
      constMeta: kIntensityRgbaConstMeta,
      argValues: [intensities],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kIntensityRgbaConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "intensity_rgba",
        argNames: ["intensities"],
      );

  Future<ImageResponse> yuvRgba({required ImageData img, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_image_data(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_yuv_rgba(port_, arg0),
      parseSuccessData: _wire2api_image_response,
      constMeta: kYuvRgbaConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kYuvRgbaConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "yuv_rgba",
        argNames: ["img"],
      );

  Future<int> colorCount({required ImageData img, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_image_data(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_color_count(port_, arg0),
      parseSuccessData: _wire2api_i64,
      constMeta: kColorCountConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kColorCountConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "color_count",
        argNames: ["img"],
      );

  Future<ImageResponse> colorClusterer({required ImageData img, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_image_data(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_color_clusterer(port_, arg0),
      parseSuccessData: _wire2api_image_response,
      constMeta: kColorClustererConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kColorClustererConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "color_clusterer",
        argNames: ["img"],
      );

  Future<ImageResponse> akazeView({required ImageData img, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_image_data(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_akaze_view(port_, arg0),
      parseSuccessData: _wire2api_image_response,
      constMeta: kAkazeViewConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAkazeViewConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "akaze_view",
        argNames: ["img"],
      );

  Future<ImageResponse> akazeFlow({required ImageData img, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_image_data(img);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_akaze_flow(port_, arg0),
      parseSuccessData: _wire2api_image_response,
      constMeta: kAkazeFlowConstMeta,
      argValues: [img],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAkazeFlowConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "akaze_flow",
        argNames: ["img"],
      );

  Future<void> resetPositionEstimate({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_reset_position_estimate(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kResetPositionEstimateConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kResetPositionEstimateConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "reset_position_estimate",
        argNames: [],
      );

  Future<String> processSensorData(
      {required String incomingData, dynamic hint}) {
    var arg0 = _platform.api2wire_String(incomingData);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_process_sensor_data(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kProcessSensorDataConstMeta,
      argValues: [incomingData],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kProcessSensorDataConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "process_sensor_data",
        argNames: ["incomingData"],
      );

  Future<SensorData> parseSensorData(
      {required String incomingData, dynamic hint}) {
    var arg0 = _platform.api2wire_String(incomingData);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_parse_sensor_data(port_, arg0),
      parseSuccessData: _wire2api_sensor_data,
      constMeta: kParseSensorDataConstMeta,
      argValues: [incomingData],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kParseSensorDataConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "parse_sensor_data",
        argNames: ["incomingData"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  Uint8List _wire2api_ZeroCopyBuffer_Uint8List(dynamic raw) {
    return raw as Uint8List;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  int _wire2api_i64(dynamic raw) {
    return castInt(raw);
  }

  ImageResponse _wire2api_image_response(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ImageResponse(
      img: _wire2api_ZeroCopyBuffer_Uint8List(arr[0]),
      msg: _wire2api_String(arr[1]),
    );
  }

  SensorData _wire2api_sensor_data(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SensorData(
      sonarFront: _wire2api_i64(arr[0]),
      sonarLeft: _wire2api_i64(arr[1]),
      sonarRight: _wire2api_i64(arr[2]),
      leftCount: _wire2api_i64(arr[3]),
      rightCount: _wire2api_i64(arr[4]),
      leftSpeed: _wire2api_i64(arr[5]),
      rightSpeed: _wire2api_i64(arr[6]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer

class NativePlatform extends FlutterRustBridgeBase<NativeWire> {
  NativePlatform(ffi.DynamicLibrary dylib) : super(NativeWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_ImageData> api2wire_box_autoadd_image_data(ImageData raw) {
    final ptr = inner.new_box_autoadd_image_data_0();
    _api_fill_to_wire_image_data(raw, ptr.ref);
    return ptr;
  }

  @protected
  int api2wire_i64(int raw) {
    return raw;
  }

  @protected
  ffi.Pointer<wire_list_labeled_image> api2wire_list_labeled_image(
      List<LabeledImage> raw) {
    final ans = inner.new_list_labeled_image_0(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      _api_fill_to_wire_labeled_image(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_image_data(
      ImageData apiObj, ffi.Pointer<wire_ImageData> wireObj) {
    _api_fill_to_wire_image_data(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_image_data(ImageData apiObj, wire_ImageData wireObj) {
    wireObj.ys = api2wire_uint_8_list(apiObj.ys);
    wireObj.us = api2wire_uint_8_list(apiObj.us);
    wireObj.vs = api2wire_uint_8_list(apiObj.vs);
    wireObj.width = api2wire_i64(apiObj.width);
    wireObj.height = api2wire_i64(apiObj.height);
    wireObj.uv_row_stride = api2wire_i64(apiObj.uvRowStride);
    wireObj.uv_pixel_stride = api2wire_i64(apiObj.uvPixelStride);
  }

  void _api_fill_to_wire_labeled_image(
      LabeledImage apiObj, wire_LabeledImage wireObj) {
    wireObj.label = api2wire_String(apiObj.label);
    wireObj.image = api2wire_uint_8_list(apiObj.image);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_train_knn(
    int port_,
    int k,
    ffi.Pointer<wire_list_labeled_image> examples,
  ) {
    return _wire_train_knn(
      port_,
      k,
      examples,
    );
  }

  late final _wire_train_knnPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.UintPtr,
              ffi.Pointer<wire_list_labeled_image>)>>('wire_train_knn');
  late final _wire_train_knn = _wire_train_knnPtr.asFunction<
      void Function(int, int, ffi.Pointer<wire_list_labeled_image>)>();

  void wire_classify_knn(
    int port_,
    ffi.Pointer<wire_uint_8_list> img,
  ) {
    return _wire_classify_knn(
      port_,
      img,
    );
  }

  late final _wire_classify_knnPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_classify_knn');
  late final _wire_classify_knn = _wire_classify_knnPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_kmeans_ready(
    int port_,
  ) {
    return _wire_kmeans_ready(
      port_,
    );
  }

  late final _wire_kmeans_readyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_kmeans_ready');
  late final _wire_kmeans_ready =
      _wire_kmeans_readyPtr.asFunction<void Function(int)>();

  void wire_training_time(
    int port_,
  ) {
    return _wire_training_time(
      port_,
    );
  }

  late final _wire_training_timePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_training_time');
  late final _wire_training_time =
      _wire_training_timePtr.asFunction<void Function(int)>();

  void wire_intensity_rgba(
    int port_,
    ffi.Pointer<wire_uint_8_list> intensities,
  ) {
    return _wire_intensity_rgba(
      port_,
      intensities,
    );
  }

  late final _wire_intensity_rgbaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_intensity_rgba');
  late final _wire_intensity_rgba = _wire_intensity_rgbaPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_yuv_rgba(
    int port_,
    ffi.Pointer<wire_ImageData> img,
  ) {
    return _wire_yuv_rgba(
      port_,
      img,
    );
  }

  late final _wire_yuv_rgbaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_ImageData>)>>('wire_yuv_rgba');
  late final _wire_yuv_rgba = _wire_yuv_rgbaPtr
      .asFunction<void Function(int, ffi.Pointer<wire_ImageData>)>();

  void wire_color_count(
    int port_,
    ffi.Pointer<wire_ImageData> img,
  ) {
    return _wire_color_count(
      port_,
      img,
    );
  }

  late final _wire_color_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_ImageData>)>>('wire_color_count');
  late final _wire_color_count = _wire_color_countPtr
      .asFunction<void Function(int, ffi.Pointer<wire_ImageData>)>();

  void wire_color_clusterer(
    int port_,
    ffi.Pointer<wire_ImageData> img,
  ) {
    return _wire_color_clusterer(
      port_,
      img,
    );
  }

  late final _wire_color_clustererPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_ImageData>)>>('wire_color_clusterer');
  late final _wire_color_clusterer = _wire_color_clustererPtr
      .asFunction<void Function(int, ffi.Pointer<wire_ImageData>)>();

  void wire_akaze_view(
    int port_,
    ffi.Pointer<wire_ImageData> img,
  ) {
    return _wire_akaze_view(
      port_,
      img,
    );
  }

  late final _wire_akaze_viewPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_ImageData>)>>('wire_akaze_view');
  late final _wire_akaze_view = _wire_akaze_viewPtr
      .asFunction<void Function(int, ffi.Pointer<wire_ImageData>)>();

  void wire_akaze_flow(
    int port_,
    ffi.Pointer<wire_ImageData> img,
  ) {
    return _wire_akaze_flow(
      port_,
      img,
    );
  }

  late final _wire_akaze_flowPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_ImageData>)>>('wire_akaze_flow');
  late final _wire_akaze_flow = _wire_akaze_flowPtr
      .asFunction<void Function(int, ffi.Pointer<wire_ImageData>)>();

  void wire_reset_position_estimate(
    int port_,
  ) {
    return _wire_reset_position_estimate(
      port_,
    );
  }

  late final _wire_reset_position_estimatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_reset_position_estimate');
  late final _wire_reset_position_estimate =
      _wire_reset_position_estimatePtr.asFunction<void Function(int)>();

  void wire_process_sensor_data(
    int port_,
    ffi.Pointer<wire_uint_8_list> incoming_data,
  ) {
    return _wire_process_sensor_data(
      port_,
      incoming_data,
    );
  }

  late final _wire_process_sensor_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_process_sensor_data');
  late final _wire_process_sensor_data = _wire_process_sensor_dataPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_parse_sensor_data(
    int port_,
    ffi.Pointer<wire_uint_8_list> incoming_data,
  ) {
    return _wire_parse_sensor_data(
      port_,
      incoming_data,
    );
  }

  late final _wire_parse_sensor_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_parse_sensor_data');
  late final _wire_parse_sensor_data = _wire_parse_sensor_dataPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_ImageData> new_box_autoadd_image_data_0() {
    return _new_box_autoadd_image_data_0();
  }

  late final _new_box_autoadd_image_data_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_ImageData> Function()>>(
          'new_box_autoadd_image_data_0');
  late final _new_box_autoadd_image_data_0 = _new_box_autoadd_image_data_0Ptr
      .asFunction<ffi.Pointer<wire_ImageData> Function()>();

  ffi.Pointer<wire_list_labeled_image> new_list_labeled_image_0(
    int len,
  ) {
    return _new_list_labeled_image_0(
      len,
    );
  }

  late final _new_list_labeled_image_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_list_labeled_image> Function(
              ffi.Int32)>>('new_list_labeled_image_0');
  late final _new_list_labeled_image_0 = _new_list_labeled_image_0Ptr
      .asFunction<ffi.Pointer<wire_list_labeled_image> Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

class wire_LabeledImage extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> label;

  external ffi.Pointer<wire_uint_8_list> image;
}

class wire_list_labeled_image extends ffi.Struct {
  external ffi.Pointer<wire_LabeledImage> ptr;

  @ffi.Int32()
  external int len;
}

class wire_ImageData extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> ys;

  external ffi.Pointer<wire_uint_8_list> us;

  external ffi.Pointer<wire_uint_8_list> vs;

  @ffi.Int64()
  external int width;

  @ffi.Int64()
  external int height;

  @ffi.Int64()
  external int uv_row_stride;

  @ffi.Int64()
  external int uv_pixel_stride;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
